---
apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: demo-synthetic-on-demand
spec:
  stages:
  - name: dev
    sequences:
    - name: "delivery"
      tasks:
        - name: "deployment"
          properties:
            deploymentstrategy: "direct"
        - name: "test"
  - name: staging
    sequences:
    - name: "delivery"
      triggeredOn:
        - event: "dev.delivery.finished"
      tasks:
        - name: "deployment"
          properties:
            deploymentstrategy: "direct"
        - name: "test"
  - name: production
    sequences:
    - name: "delivery"
      triggeredOn:
        - event: "staging.delivery.finished"
      tasks:
        - name: "deployment"
          properties:
            deploymentstrategy: "direct"
        - name: "test"
