
---
spec_version: "0.1.1"
comparison:
  aggregate_function: "avg"
  compare_with: "single_result"
  include_result_with_score: "pass"
  number_of_comparison_results: 1
filter:
objectives:
  - sli: "e2e_page_load"
    displayName: "E2E page load time"
    pass:
      - criteria:
          - "<1500"
    warning:
      - criteria:
          - "<3000"
    weight: 1
  - sli: "e2e_version"
    displayName: "E2E version load time"
    pass:
      - criteria:
          - "<1500"
    warning:
      - criteria:
          - "<3000"
    weight: 1
  - sli: "e2e_synthetic_success_rate"
    displayName: "E2E Synthetic test success rate"
    pass:
      - criteria:
          - ">80"
    warning:
      - criteria:
          - ">50"
    weight: 1
  - sli: "response_time"
    displayName: "Response Time 95th Percentile"
    key_sli: false
    pass:             # pass if (relative change <= 10% AND absolute value is < 600ms)
      - criteria:
          - "<=+10%"  # relative values require a prefixed sign (plus or minus)
          - "<800000"    # absolute values only require a logical operator
    warning:          # if the response time is below 800ms, the result should be a warning
      - criteria:
          - "<=1000000"
    weight: 1
  - sli: "response_time_invoke_api"
    displayName: "Response Time Invoke API Method"
    key_sli: false
    weight: 2
    pass:
      - criteria:
          - "<=+10%"
          - "<850000"
    warning:
      - criteria:
          - "<=+20%"
          - "<=1000000"
  - sli: "failure_rate"
    displayName: "Error Rate"
    pass:
      - criteria:
          - "<=+5%"
          - "<2"
    warning:
      - criteria:
          - "<5"
    weight: 2
  - sli: "pg_heap_suspension"
    displayName: "Process Heap Suspension"
    pass:
      - criteria:
          - "<100"
    warning:
      - criteria:
          - "<200"
    weight: 1
  - sli: "pg_cpu_usage"
    displayName: "Process CPU Usage"
    pass:
      - criteria:
          - "<20"
    warning:
      - criteria:
          - "<50"
    weight: 1
total_score:
  pass: "90%"
  warning: "75%"
