---
- include_tasks: roles/gitlab/tasks/source-secret.yml

- include_tasks: roles/gitlab/tasks/ensure-group.yml

- block:
  - name: Source Keptn secrets
    include_role:
      name: keptn
      tasks_from: source-secret
  - include_role:
      name: keptn
      tasks_from: source-endpoints
  - set_fact:
      ca_endpoint: "{{ keptn_endpoint }}"
      ca_bridge: "{{ keptn_bridge }}"
      ca_api_token: "{{ keptn_api_token }}"
  when: cloud_automation_flavor is defined and cloud_automation_flavor == "KEPTN"

- block:
  - name: Source Cloud Automation secrets
    include_role:
      name: cloudautomation
      tasks_from: source-secret
  - set_fact:
      ca_endpoint: "{{ cloud_automation_endpoint }}"
      ca_bridge: "{{ cloud_automation_bridge }}"
      ca_api_token: "{{ cloud_automation_api_token }}"
  when: cloud_automation_flavor is defined and cloud_automation_flavor == "CLOUD_AUTOMATION"

- block:
  - name: Source Kubernetes endpoint
    kubernetes.core.k8s_info:
      kind: Service
      name: "kubernetes"
      namespace: "default"
    register: kubernetes_svc_data
  - set_fact:
      kubernetes_api_endpoint: "https://{{ kubernetes_svc_data.resources[0].spec.clusterIP }}"

- block:
  - name: Source Dynatrace Operator ServiceAccount
    kubernetes.core.k8s_info:
      kind: ServiceAccount
      name: "dynatrace-kubernetes-monitoring"
      namespace: "dynatrace"
    register: dt_operator_sa_data
  - name: Source Dynatrace Operator Secret
    kubernetes.core.k8s_info:
      kind: Secret
      name: "{{ dt_operator_sa_data.resources[0].secrets[0].name }}"
      namespace: "dynatrace"
    register: dt_operator_secret_data
  - set_fact:
      dt_operator_kube_bearer_token: "{{ dt_operator_secret_data.resources[0].data.token | b64decode }}"

- name: Source DT Synthetic node id
  include_role:
    name: dt-activegate
    tasks_from: source-node-id

- name: Gitlab - Create variables
  include_role:
    name: gitlab
    tasks_from: ensure-group-var
  vars:
    gitlab_var_key: "{{ item.key }}"
    gitlab_var_value: "{{ item.value }}"
  loop:
    - { key: 'INGRESS_DOMAIN', value: '{{ ingress_domain }}' }
    - { key: 'INGRESS_PROTOCOL', value: '{{ ingress_protocol }}' }
    - { key: 'KEPTN_API_TOKEN', value: '{{ ca_api_token | default(None) }}' }
    - { key: 'KEPTN_ENDPOINT', value: '{{ ca_endpoint | default(None) | replace("/api","") }}' }
    - { key: 'DT_TENANT_URL', value: '{{ dynatrace_tenant_url }}' }
    - { key: 'DT_API_TOKEN', value: '{{ dynatrace_api_token }}' }
    - { key: 'KUBE_BEARER_TOKEN', value: '{{ dt_operator_kube_bearer_token | default(None) }}' }
    - { key: 'KUBE_API_ENDPOINT', value: '{{ kubernetes_api_endpoint | default(None) }}' }
    - { key: 'SYNTH_NODE_ID', value: '{{ dt_synthetic_node_id | default(None) }}' }
