---
- name: Source Gitlab secret
  kubernetes.core.k8s_info:
    kind: Secret
    name: "gitlab-gitlab-initial-root-password"
    namespace: "{{ gitlab_namespace }}"
  register: gitlab_secret_data

- name: Set secrets facts
  set_fact:
    gitlab_username: "root"
    gitlab_password: "{{ gitlab_secret_data.resources[0].data.password | b64decode }}"
  when: gitlab_secret_data is defined and gitlab_secret_data.resources[0] is defined

- name: Gitlab - Get new OAuth token
  uri:
    url: "{{ gitlab_internal_endpoint }}/oauth/token"
    validate_certs: false
    method: POST
    status_code: [200, 201]
    headers:
      Content-Type: "application/json"
    body:
      grant_type: "password"
      username: "{{ gitlab_username }}"
      password: "{{ gitlab_password }}"
    body_format: json
  register: gitlab_oauth_token_result

- name: Gitlab - Set gitlab_oauth_token
  set_fact:
    gitlab_oauth_token: "{{ gitlab_oauth_token_result.json.access_token }}"
