plugins_dependencies = %w( vagrant-hostmanager vagrant-disksize vagrant-docker-compose )
plugin_status = false
plugins_dependencies.each do |plugin_name|
  unless Vagrant.has_plugin? plugin_name
    system("vagrant plugin install #{plugin_name}")
    plugin_status = true
    puts " #{plugin_name}  Dependencies installed"
  end
end

if plugin_status === true
  exec "vagrant #{ARGV.join' '}"
else
  puts "All Plugin Dependencies already installed"
end

require 'yaml'
vmconfig = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"
    config.hostmanager.enabled = true
    config.hostmanager.include_offline = true
    config.hostmanager.manage_host = true
    config.vm.provision :hostmanager
  
    config.vm.define "ace-box" do |c|
      c.vm.hostname = "ace-box"
      c.vm.network "private_network", ip: vmconfig["acebox"]["specs"]["priv_ip"]
      c.disksize.size = vmconfig["acebox"]["specs"]["disk"]
      c.vm.provision "ansible", run: "always" do |ansible|
        ansible.become = true
        ansible.playbook = "ansible/initial.yml"
        # [KR] below is used to install the OneAgent ansible role, replaced with helm chart
        #ansible.galaxy_role_file = "ansible/requirements.yml"
        #ansible.galaxy_roles_path = "/etc/ansible/roles"
        #ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --force"
      end
      c.vm.provider vmconfig["vagrant"]["provider"] do |pr|
        pr.memory = vmconfig["acebox"]["specs"]["mem"]
        pr.cpus = vmconfig["acebox"]["specs"]["cpu"]
      end
      c.vm.post_up_message = "Please open http://ace-box:30001 and use links"
    end
  
  end 