plugins_dependencies = %w( vagrant-hostmanager vagrant-disksize vagrant-docker-compose vagrant-vbguest)
plugin_status = false
plugins_dependencies.each do |plugin_name|
  unless Vagrant.has_plugin? plugin_name
    system("vagrant plugin install #{plugin_name}")
    plugin_status = true
    puts " #{plugin_name}  Dependencies installed"
  end
end

if plugin_status === true
  exec "vagrant #{ARGV.join' '}"
else
  puts "All Plugin Dependencies already installed"
end

require 'yaml'
vmconfig = YAML.load_file('config.yml')

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
    config.hostmanager.enabled = true
    config.hostmanager.include_offline = true
    config.hostmanager.manage_host = true
    config.vm.provision :hostmanager
  
    config.vm.define "ace-box" do |c|
      c.vm.hostname = "ace-box"
      c.vm.network "private_network", ip: vmconfig["acebox"]["specs"]["priv_ip"]
      c.disksize.size = vmconfig["acebox"]["specs"]["disk"]

      config.vm.provision "shell", inline: "sudo apt-get update -y"
      config.vm.provision "shell", inline: "sudo apt-get upgrade -y"
      config.vm.provision "shell", inline: "sudo apt-get install python3.8 python3-pip -y"
      config.vm.provision "shell", inline: "python3.8 -m pip install --upgrade pip -q"
      config.vm.provision "shell", inline: "python3.8 -m pip install ansible -q"
      
      c.vm.provision "ansible_local" do |ansible|
        ansible.install = false
        ansible.become = true
        ansible.playbook = "ansible/initial.yml"
        # ansible.verbose = true # enable to get more logging
        ansible.compatibility_mode = "2.0"
        ansible.extra_vars = {
          ansible_python_interpreter: "auto",
          acebox_provisioner: "vagrant",
          non_root_user: "vagrant"
        }
      end

      c.vm.provider "virtualbox" do |pr|
        pr.memory = vmconfig["acebox"]["specs"]["mem"]
        pr.cpus = vmconfig["acebox"]["specs"]["cpu"]
        pr.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

      c.vm.post_up_message = "Please open http://dashboard.#{vmconfig["acebox"]["specs"]["priv_ip"]}.#{vmconfig["acebox"]["config"]["microk8s"]["domain_ext"]} and use links"
    end
  end 