---
- include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "demo_monaco_gitops"
    var_value_to_set: true

- include_role:
    name: microk8s

- include_role:
    name: dt-activegate

- include_role:
    name: dt-oneagent

- include_role:
    name: monaco

- include_role:
    name: monaco
    tasks_from: dt-cleanup

- include_role:
    name: gitea

# - include_role:
#     name: keptn
#   when: cloud_automation_flavor is defined and cloud_automation_flavor == "KEPTN"

# - include_role:
#     name: cloudautomation
#   when: cloud_automation_flavor is defined and cloud_automation_flavor == "CLOUD_AUTOMATION"

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "{{ demo_monaco_gitops_org }}"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "{{ demo_monaco_gitops_org }}"
    gitea_repo: "{{ demo_monaco_gitops_repo_name }}"

- include_role:
    name: repository
  vars:
    repo_src: "{{ item.repo_src }}"
    git_org: "{{ item.git_org }}"
    git_repo: "{{ item.repo_target }}"
    git_username: "{{ gitea_username }}"
    git_password: "{{ gitea_password }}"
    git_remote: "gitea"
  loop:
  - { repo_target: "{{ demo_monaco_gitops_repo_name }}", repo_src: "{{ role_path }}/files/repos/monaco", git_org: "{{ demo_monaco_gitops_org }}" }
  when: new_repo_created is defined and new_repo_created == true

- include_role:
    name: otel-collector

# Include use case specific Jenkins values
- set_fact:
    include_jenkins_value_file: "{{ role_path }}/templates/demo-monaco-jobs.yml.j2"

- include_role:
    name: jenkins
    tasks_from: template-values-file
  vars:
    demo_repo: "{{ demo_monaco_gitops_repo_name }}"
    demo_org: "{{ demo_monaco_gitops_org }}"
    demo_jenkins_folder: "{{ demo_monaco_gitops_folder }}"
    git_domain: "gitea.{{ ingress_domain }}"

- include_role:
    name: jenkins

- include_role:
    name: dashboard
