---
- name: Create Dynatrace secret
  ansible.builtin.command: "keptn create secret dynatrace --scope=dynatrace-service --from-literal=DT_TENANT={{ dynatrace_tenant_url }} --from-literal=DT_API_TOKEN={{ dynatrace_api_token }}"
  ignore_errors: true

- name: Deploy Keptn Dynatrace service
  kubernetes.core.helm:
    name: dynatrace-service 
    chart_ref: "https://github.com/keptn-contrib/dynatrace-service/releases/download/{{ keptn_dynatrace_service_version }}/dynatrace-service-{{ keptn_dynatrace_service_version }}.tgz"
    release_namespace: "{{ keptn_namespace }}"
    create_namespace: true
    wait: true
    wait_timeout: 15m
    values:
      dynatraceService:
        config:
          keptnApiUrl: "{{ ingress_protocol }}://{{ keptn_ingress_domain }}/api"
          keptnBridgeUrl: "{{ ingress_protocol }}://{{ keptn_ingress_domain }}/bridge"
      distributor:
        image:
          tag: "{{ keptn_version }}"
