---
apiVersion: v2
actions:
  - name: "Wait for evaluation result"
    events:
      - name: "sh.keptn.event.evaluation.triggered"
    tasks:
      - name: "Run waiter script"
        files:
          - keptn_eval_result.py
        image: "python:3.9-alpine"
        workingDir: "/keptn"
        cmd:
          - python
        args:
          - 'keptn_eval_result.py'
        env:
          - name: KEPTN_DEBUG
            valueFrom: string
            value: "1"
          - name: EVENT
            value: "$"
            valueFrom: event

# keptn add-resource --project=simplenode-gitlab --service=simplenodeservice --stage=staging --resource=job_config.yaml --resourceUri=job/config.yaml
# keptn add-resource --project=simplenode-gitlab --service=simplenodeservice --stage=staging --resource=keptn_eval_result.py --resourceUri=keptn_eval_result.py