include:
  - remote: 'https://gitlab.com/dynatrace-ace/keptn-gitlab-library/-/raw/master/jmeter_run_test.yaml'
  - remote: 'https://gitlab.com/dynatrace-ace/dynatrace-gitlab-library/-/raw/master/dynatrace_event.yaml'

variables:
  BUILD_ID: '1'  # 1, 2, 3 or 4
  DT_RELEASE_VERSION: 'v$BUILD_ID.0.0'
  DT_RELEASE_BUILD_VERSION: '$BUILD_ID.0.0'
  DT_RELEASE_PRODUCT: 'simplenode-app'
  DT_RELEASE_STAGE: 'simplenode-gitlab-staging'

stages:
  - init
  - deploy
  - test
  - eval

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"

monaco:
  image: dynatraceace/monaco-runner:release-v1.6.0
  stage: init
  script:
    - monaco -v -dry-run -e=mac/environments.yaml -p=infrastructure mac/projects
    - monaco -v -e=mac/environments.yaml -p=infrastructure mac/projects
    - monaco -v -dry-run -e=mac/environments.yaml -p=ace mac/projects
    - monaco -v -e=mac/environments.yaml -p=ace mac/projects

init_keptn:
  image: dynatraceace/keptn-gitlab-runner:2.1
  stage: init
  variables: 
    KEPTN_PROJECT: simplenode-gitlab
    KEPTN_SERVICE: simplenodeservice
    KEPTN_STAGE: staging
    KEPTN_SOURCE: gitlab
    KEPTN_MONITORING: dynatrace
    SHIPYARD_FILE: cloudautomation/shipyard.yaml
    SLO_FILE: cloudautomation/slo.yaml
    SLI_FILE: cloudautomation/sli.yaml
    DT_CONFIG_FILE: cloudautomation/dynatrace.conf.yaml
  script:
    - /keptn/keptn_init.sh
  artifacts:
    paths: 
    - keptn.init.json

deployment:
  image: dtzar/helm-kubectl
  stage: deploy
  script:
    - >
      helm upgrade --install simplenode-gitlab-staging helm/simplenodeservice 
      --set image="dynatraceace/simplenodeservice:$DT_RELEASE_BUILD_VERSION"
      --set domain="$INGRESS_DOMAIN" 
      --set version="$DT_RELEASE_VERSION"
      --set build_version="$DT_RELEASE_BUILD_VERSION" 
      --set environment="$DT_RELEASE_STAGE" 
      --namespace "$DT_RELEASE_STAGE" --create-namespace 
      --wait


# dynatrace_info_event:
#   extends: .dynatrace_event
#   stage: deploy
#   variables:
#     DESCRIPTION: "An INFO event"
#     CUSTOM_PROPERTIES: '{"label1":"foo","label2":"bar"}'
#     EVENT_TYPE: "CUSTOM_INFO"
#     TITLE: "My Event Title"

# dynatrace_deploy_event:
#   extends: .dynatrace_event
#   stage: deploy
#   variables:
#     DESCRIPTION: "A DEPLOY event"
#     CUSTOM_PROPERTIES: '{"label1":"foo","label2":"bar"}'
#     EVENT_TYPE: "CUSTOM_DEPLOYMENT"
#     DEPLOYMENT_NAME: "simplenode_gitlab"
#     DEPLOYMENT_VERSION: "1.0.0"
#     REMEDIATION_ACTION: "http://google.com"

# dynatrace_annotation_event:
#   extends: .dynatrace_event
#   stage: deploy
#   variables:
#     DESCRIPTION: "An ANNOTATION event"
#     CUSTOM_PROPERTIES: '{"label1":"foo","label2":"bar"}'
#     EVENT_TYPE: "CUSTOM_ANNOTATION"
#     ANNOTATION_TYPE: "My Custom annotation"
#     ANNOTATION_DESCRIPTION: "I want to annotate something"
  
# dynatrace_config_event:
#   extends: .dynatrace_event
#   stage: deploy
#   variables:
#     DESCRIPTION: "A CONFIG event"
#     CUSTOM_PROPERTIES: '{"label1":"foo","label2":"bar"}'
#     EVENT_TYPE: "CUSTOM_CONFIGURATION"
#     CONFIGURATION: "I Set Something to 1"
#     ORIGINAL: "It was 0" 


run-tests:
  before_script: 
    - echo $(date --utc +%FT%T.000Z) > keptn.test.starttime
  after_script: 
    - echo $(date --utc +%FT%T.000Z) > keptn.test.endtime
  stage: test
  variables: 
    LOCUST_LOCUSTFILE: locust/locustfile.py
    LOCUST_CONFIG: locust/locust.conf
    LOCUST_HOST: '$INGRESS_PROTOCOL://simplenodeservice.$DT_RELEASE_STAGE.$INGRESS_DOMAIN'
    LOCUST_LOAD_TEST_NAME: 'Loadtest - $DT_RELEASE_BUILD_VERSION'
  image: locustio/locust
  script:
    - locust --config $LOCUST_CONFIG --locustfile $LOCUST_LOCUSTFILE --host $LOCUST_HOST
  artifacts:
    paths:
    - keptn.test.starttime
    - keptn.test.endtime

quality_gate:
  image: dynatraceace/keptn-gitlab-runner:2.1
  stage: eval
  script:
    - export KEPTN_LABELS='[{"DT_RELEASE_VERSION":"'${DT_RELEASE_VERSION}'"},{"DT_RELEASE_BUILD_VERSION":"'${DT_RELEASE_BUILD_VERSION}'"},{"DT_RELEASE_STAGE":"'${DT_RELEASE_STAGE}'"},{"DT_RELEASE_PRODUCT":"'${DT_RELEASE_PRODUCT}'"}]'
    - /keptn/keptn_eval.sh
