---
- name: Enable "demo_synthetic"
  include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "demo_synthetic"
    var_value_to_set: true

- name: Set "ingress_class"
  include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "ingress_class"
    var_value_to_set: "istio"

- include_role:
    name: k3s

- include_role:
    name: istio

- include_role:
    name: dt-oneagent

- include_role:
    name: keptn
  vars:
    keptn_version: "0.16.0"
    keptn_dynatrace_service_version: "0.22.0"
    keptn_jmeter_service_enabled: false
    keptn_helm_service_enabled: true
    keptn_synthetic_service_enabled: true
    keptn_test_collector_service_enabled: true
    keptn_job_executor_service_enabled: true
    keptn_job_executor_service_subscriptions: "sh.keptn.event.test.triggered"

- include_role:
    name: gitea

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "demo"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "demo"
    gitea_repo: "synthetic-on-demand"

- name: Prepare CA use case
  block:
  - name: Create Project
    ansible.builtin.command: "keptn create project demo-synthetic-on-demand --shipyard={{ role_path }}/files/shipyard.yaml --git-user={{ gitea_username }} --git-token={{ gitea_access_token }} --git-remote-url={{ gitea_internal_endpoint }}/demo/synthetic-on-demand.git"
    ignore_errors: true
  - name: Create Service
    ansible.builtin.command: "keptn create service simplenodeservice --project=demo-synthetic-on-demand"
    ignore_errors: true
  - name: Upload Delivery Helm Chart
    ansible.builtin.command: "keptn add-resource --project=demo-synthetic-on-demand --service=simplenodeservice --all-stages --resource={{ role_path }}/files/helm/simplenodeservice.tgz --resourceUri=helm/simplenodeservice.tgz"
    ignore_errors: true
  - name: Upload dynatrace.conf.yaml
    ansible.builtin.command: "keptn add-resource --project=demo-synthetic-on-demand --resource={{ role_path }}/files/dynatrace.conf.yaml --resourceUri=dynatrace/dynatrace.conf.yaml"
    ignore_errors: true
  - name: Configure Dynatrace monitoring
    ansible.builtin.command: "keptn configure monitoring dynatrace --project=demo-synthetic-on-demand"
    ignore_errors: true
  - name: Upload Job Executor resources
    ansible.builtin.command: "keptn add-resource --project=demo-synthetic-on-demand --service=simplenodeservice --all-stages --resource={{ role_path }}/files/job_config.yaml --resourceUri=job/config.yaml"
    ignore_errors: true
  - ansible.builtin.command: "keptn add-resource --project=demo-synthetic-on-demand --service=simplenodeservice --all-stages --resource={{ role_path }}/files/locust.conf --resourceUri=locust/locust.conf"
    ignore_errors: true
  - ansible.builtin.command: "keptn add-resource --project=demo-synthetic-on-demand --service=simplenodeservice --all-stages --resource={{ role_path }}/files/locustfile.py --resourceUri=locust/locustfile.py"
    ignore_errors: true

    # keptn trigger delivery --project=demo-synthetic-on-demand --service=simplenodeservice --image=dynatraceace/simplenodeservice:1.0.2

- include_role:
    name: dashboard
