---
- name: Enable "demo_synthetic"
  include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "demo_synthetic"
    var_value_to_set: true

- include_role:
    name: microk8s

- include_role:
    name: dt-oneagent

- include_role:
    name: monaco

- include_role:
    name: monaco
    tasks_from: dt-cleanup

- include_role:
    name: keptn
  vars:
    keptn_version: "0.16.0"
    keptn_dynatrace_service_version: "0.22.0"

- include_role:
    name: gitea

- include_role:
    name: gitea
    tasks_from: source-secret
  when: gitea_access_token is not defined or gitea_username is not defined or gitea_password is not defined

- include_role:
    name: gitea
    tasks_from: create-organization
  vars:
    gitea_org: "demo"

- include_role:
    name: gitea
    tasks_from: create-repository
  vars:
    gitea_org: "demo"
    gitea_repo: "synthetic-on-demand"

- include_role:
    name: dashboard
