---
- hosts: localhost
  connection: local
  become: true
  become_user: "{{ ace_box_user | default(lookup('env','USER')) }}"
  vars:
    ace_config_file_path: "./ace.config.yml"
  roles:
  # Role "config-v2" is always executed 
  # and makes sure that all previous settings 
  # are sourced alongside newly enabled/disabled
  - role: config-v2

  # Use case - All demo
  - role: demo-all
    tags:
    - demo_all
    - never

  # Use case - Quality Gates with Jenkins demo
  - role: demo-quality-gates-jenkins
    tags:
    - demo_default
    - demo_quality_gates_jenkins
    - never

  # Use case - Security Gates with Jenkins demo
  - role: demo-security-gates-jenkins
    tags:
    - demo_security_gates_jenkins
    - never

  # Use case - Auto remediation demo
  - role: demo-auto-remediation-ansible
    tags:
    - demo_auto_remediation_ansible
    - never
  
  # Use case - Quality Gates with Gitlab demo
  - role: demo-quality-gates-gitlab
    tags:
    - demo_quality_gates_gitlab
    - never
  
  # Use case - Monaco GitOps demo
  - role: demo-monaco-gitops
    tags:
    - demo_monaco_gitops
    - never

  # Use case - AppSec HOT
  - role: hot-appsec
    tags:
    - hot_appsec
    - never

  # Use case - Monaco GitOps hands-on training
  # - role: hot-monaco-gitops
  #   tags:
  #   - monaco_gitops
  #   - never
  
  # Use case - Quality Gates hands-on training
  # - role: hot-quality-gates
  #   tags:
  #   - quality_gates
  #   - never

  # External use case
  - role: use-case-ext
    tags:
    - use_case_ext
    - never