---
- include_role:
    name: config-v2
    tasks_from: set-var
  vars:
    var_key_to_set: "demo_all"
    var_value_to_set: true

# Certain values are only templated as a first step, their
# deployment is skipped.
# This speeds up the overall deployment process as such tools
# are not installed all over again for each demo
- set_fact:
    jenkins_skip_install: True
    dashboard_skip_install: True

- include_role:
    name: demo-quality-gates-jenkins

- include_role:
    name: demo-security-gates-jenkins

- include_role:
    name: demo-quality-gates-gitlab

- include_role:
    name: demo-monaco-gitops

# Last role also installs Jenkins, Dashboard, ...
- set_fact:
    jenkins_skip_install: False
    dashboard_skip_install: False

- include_role:
    name: demo-auto-remediation-ansible
