---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "api"
    app.kubernetes.io/version: "{{ .Values.version }}"
    app.kubernetes.io/managed-by: "Helm"
    chart: "{{ .Chart.Name }}"
    app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/version: "{{ .Values.version }}"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/part-of: "{{ .Values.keptn.project }}"
        app.kubernetes.io/component: "api"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        env:
        - name: KEPT_PROJECT
          value: "{{ .Values.keptn.project }}"
        - name: KEPT_STAGE
          value: "{{ .Values.keptn.stage }}"
        - name: KEPT_SERVICE
          value: "{{ .Values.keptn.service }}"
        - name: DT_RELEASE_VERSION
          value: "{{ .Values.version }}"
        - name: DT_RELEASE_BUILD_VERSION
          value: "{{ .Values.version }}"
        - name: DT_RELEASE_PRODUCT
          value: "{{ .Values.keptn.service }}"
        - name: DT_RELEASE_STAGE
          value: "{{ .Values.keptn.stage }}"
        - name: DT_TAGS
          value: {{ .Values.dt_tags }}
        - name: DT_CUSTOM_PROP
          value: "RELEASE_BUILD_VERSION={{ .Values.version }} RELEASE_STAGE={{ .Values.keptn.stage }}"
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 15
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
      nodeSelector:
        beta.kubernetes.io/os: linux